services:
  backend:
    build:
      context: ./backend
    container_name: seriusbrand-backend-prod
    ports:
      - "8081:8081" # Map host 8081 to container 8081
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - PORT=8081
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=seriusbrand
      - DB_PORT=5432
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    container_name: seriusbrand-db-prod
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=seriusbrand
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: "https://home.seriusmen.online/api"
    container_name: seriusbrand-frontend-prod
    ports:
      - "80:80"
      - "443:443" # Expose HTTPS port
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro # Mount SSL certificates from host
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
